### ISSUE TITLE
Commands google, youtube, wolframalpha, weather

### ISSUE THREAD

**Issue by ampc** [MenfiosINC/MenfiosSlackBot#3]
!g - google search
!yt - youtube search
!wa - wolframalpha :whale: 
!wt porto - weather :partly_sunny: 

---

random quote do lopson.txt por dia :)

**Comment by eSoares** [comment]
Já implementados:
- [x] !g - google search
- [x] !yt - youtube search
- [x] !wa - wolframalpha :whale: 
- [x] !wt porto - weather :partly_sunny:

**Comment by eSoares** [comment]
No caso do wolframalpha tens algum esboço de comandos? 
Qual o limite de ouput? 2 linhas?

**Comment by eSoares** [comment]
- [x]  Youtube não está a funcionar.
- [x]  Adicionar títulos no resultado do google search;
- [x] Links do youtube resultado do google search não funcionam por causa os caracteres escapados
