### ISSUE TITLE
Add search and replace

### ISSUE THREAD

**Issue by eSoares** [MenfiosINC/MenfiosSlackBot#8]
support for s/stuff/more stuff

Example of usage: 
beta> hey dude, check this stuff
alfa> s/stuff/more stuff
bot> beta: hey dude, check this more stuff

**Comment by josemaia** [comment]
fr: allow for b/foo/bar/ syntax as well

**Comment by eSoares** [comment]
@josemaia can you provide an example of how it should work?

**Comment by josemaia** [comment]
<lopes> hello, friends
<tony> b/friends/colleagues/
<bot> lopes: hello, colleagues

**Comment by eSoares** [comment]
Isn't that the same as "s/stuff/more stuff" ?

**Comment by josemaia** [comment]
yes, just nice to have an alternative  syntax
